[profile]
title = "Citation Index"
description = "Citation only for an XML file"

[[view_task_templates]]
view_key = "citation"
description = "Citation"

[view_task_templates.task_template]
bin_path = "${PMRPLATFORM_DIR}/target/release/pmr-citation"
version_id = "0.0.1"

[[view_task_templates.task_template.args]]
flag = "rdfxml"
flag_joined = false
flag_omit_when_null = false
choice_fixed = false

[[view_task_templates.task_template.args]]
flag = "index"
flag_joined = false
flag_omit_when_null = false
choice_fixed = false

[[view_task_templates.task_template.args]]
flag = "--input-path="
flag_joined = true
flag_omit_when_null = false
prompt = ""
default = "workspace_file_path"
choice_fixed = true
choice_source = "workspace_file_path"
choices = []

[[view_task_templates.task_template.args]]
flag = "--exposure-id="
flag_joined = true
flag_omit_when_null = false
prompt = ""
default = "exposure_id"
choice_fixed = true
choice_source = "exposure_id"
choices = []

[[view_task_templates.task_template.args]]
flag = "--exposure-path="
flag_joined = true
flag_omit_when_null = false
prompt = ""
default = "exposure_file"
choice_fixed = true
choice_source = "exposure_file"
choices = []
